name: 'dbt_analytics_stack'
version: '1.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
data-paths: ["data"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt_analytics_stack:
    staging:
      materialized: view
    marts:
      materialized: table
